language: csharp  
sudo: required  
dist: trusty  
addons:
    postgresql: "9.6"
services:
    - postgresql
dotnet: 1.0.1

mono:
  - 4.6.1
  - 4.8.1
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"

os:  
  - linux
  #- osx # times out too often, enable at own risk


env:
  - POSTGRES_DB=postgres POSTGRES_USER=postgres POSTGRES_PASSWORD= POSTGRES_HOST=localhost

before_script:
  # https://stackoverflow.com/questions/11584749/how-to-create-a-new-database-with-the-hstore-extension-already-installed
  - psql -d template1 -c 'create extension if not exists plv8;'
  - chmod a+x ./build.sh

script:  
  - ./build.sh


matrix:
  allow_failures:
    - mono: latest
    - mono: alpha
    - mono: beta
    - mono: weekly
