language: csharp  
sudo: required  
dist: trusty  
addons:
    postgresql: "9.6"
services:
    - postgresql
dotnet: 1.0.1
mono: latest
os:  
  - linux
  #- osx # times out too often, enable at own risk


env:
  - POSTGRES_DB=postgres POSTGRES_USER=postgres POSTGRES_PASSWORD= POSTGRES_HOST=localhost

script:  
  - ./build.sh
