environment:

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd

test: off

version: 0.0.1.{build}

artifacts:
  - path: bin
    name: bin

environment: 
  POSTGRES_PASS: "Password12!"
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.5
  PG_PLV8_EXTENSION_ZIP_FILENAME: pg95plv8jsbin_w64

services:
  - postgresql95

install:
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%
  - curl -L -O -S -s http://www.postgresonline.com/downloads/%PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - 7z x %PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - xcopy /s /y /d %PG_PLV8_EXTENSION_ZIP_FILENAME% "%POSTGRES_PATH%\"

before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - psql -d template1 -c "create extension if not exists plv8;"
