init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
services:
  - postgresql95
environment: 
  POSTGRES_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASS: Password12!
  POSTGRES_HOST: postgres